### ISSUE TITLE
Static archiver call does not use command file

### ISSUE THREAD

**Issue by JuergenHaug** [gradle/gradle-native#1028]
The "old native build" fails to create a static archive due the 32k command line limit. 

`Program 'arm-none-eabi-ar.exe' failed to run: The filename or extension is too longAt line:1 char:1`      

The invocation of the compiler and linker use command files, can that be activated for the archiver too ? I did some digging in the code and using the [GccOptionsFileArgsWriter](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/GccOptionsFileArgsWriter.java) for [ArStaticLibraryArchiver](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/ArStaticLibraryArchiver.java) seems to do the trick.

Unfortunately we are cross-compiling a C application. My impression is, that is it is too early to migrate to the new native build for this case.

### Expected Behavior
Call to static archiver of gcc should use command file. 

### Current Behavior
Arguments are passed via command line and will eventually hit the 32k limit.

### Context
Creating a static archive from ~25 object files. The files are passed using absolute paths, which makes the command line call too large.

### Your Environment
cross compiling c application using arm gcc, gradle 5.5, Win10

**Comment by lacasseio** [comment]
Thanks for reporting this issue and I agree the `ar` could use a command file. The broader question is if every `ar` tool support command file. I think we can try to make the change and see where the tests may be failing. Would you be willing to help with this? Here are the steps I think we can so to solve this issue:
- Write an integration test in language native for all the language that would generate a 32k command line and make sure it's failing.
- Modify the [`ArStaticLibraryArchiver` constructor](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/ArStaticLibraryArchiver.java#L40-L41) to take `useCommandFile` like his [`GccCompatibleNativeCompiler` sibling](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/GccCompatibleNativeCompiler.java#L37-L38). Pass the variable to the superclass constructor instead of `false`.
- Pass `false` for `useCommandFile` in [`SwiftPlatformToolProvider`](https://github.com/gradle/gradle/blob/36614ee523e5906ddfa1fed9a5dc00a5addac1b0/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/swift/SwiftPlatformToolProvider.java#L110) (we can try to pass `true` but let's leave Swift outside the scope of this issue).
- Pass `useCommandFile` variable inside  [`GccPlatformToolProvider`](https://github.com/gradle/gradle/blob/bd566cbd443d9fa060321f73d21f9c68064fe822/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/GccPlatformToolProvider.java#L189).
- Replace [`ArStaticLibraryArchiver#addOptionsFileArgs` method content](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/ArStaticLibraryArchiver.java#L77) with [`GccCompatibleNativeCompiler#addOptionsFileArgs` content](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/GccCompatibleNativeCompiler.java#L48-L50). We can deal with the code duplication later.
- Run the unit and integration test for the platform-native and language-native: `./gradlew :platformNative:check :languageNative:check --continue`.
- Fix any issues that are coming from the fact that we are now using the command file instead of the raw command line.
- Make sure the integration test for the 32k command line is now passing.
- Submit PR :-)

That would be really helpful. I can take care of porting the integration test to the new native plugins.

**Comment by jbelle** [comment]
Hi, I'd like to help resolve this issue.
I implemented an integration test that generates many source files and builds a library with the `cpp-library` plugin. The command line for the `ar` static library archiver then exceeds the windows command line length limit and the test fails on windows. With your proposed changes to `ArStaticLibraryArchiver` the test passes.
As far as I can tell from the test results of platform-native and language-native, these changes don't introduce any further issues.
Please let me know how I can proceed.

**Comment by BigPapa314** [comment]
This issue still exists in gradle 7.5.1 ist there any plan to proceed?
